---
service: es-imputation-sg
provider:
  name: aws
  role: arn:aws:iam::${self:custom.accountId}:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.SubnetId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.SubnetId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

functions:
  deploy-apply-factors-wrangler:
    name: es-apply-factors-wrangler
    handler: apply_factors_wrangler.lambda_handler
    package:
      include:
        - apply_factors_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      in_file_name: calculate_factors_out.json
      incoming_message_group: imputation-calculate-factors-out
      method_name: es-apply-factors-method
      non_responder_file: non_responders_output.json
      out_file_name: apply_factors_out.json
      period: 201809
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputation-apply-factors-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-apply-factors-method:
    name: es-apply-factors-method
    handler: apply_factors_method.lambda_handler
    package:
      include:
        - apply_factors_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-atypicals-wrangler:
    name: es-atypicals-wrangler
    handler: atypicals_wrangler.lambda_handler
    package:
      include:
        - atypicals_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      atypical_columns: atyp601,atyp602,atyp603,atyp604,atyp605,atyp606,atyp607
      bucket_name: results-s3-bucket
      in_file_name: iqrs_out.json
      incoming_message_group: imputation-iqrs-out
      method_name: es-atypicals-method
      out_file_name: atypicals_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputation-atypicals-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-atypicals-method:
    name: es-atypicals-method
    handler: atypicals_method.lambda_handler
    package:
      include:
        - atypicals_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      atypical_columns: atyp601,atyp602,atyp603,atyp604,atyp605,atyp606,atyp607
      iqrs_columns: iqrs601,iqrs602,iqrs603,iqrs604,iqrs605,iqrs606,iqrs607
      mean_columns: mean_Q601_asphalting_sand,mean_Q602_building_soft_sand,mean_Q603_concreting_sand,mean_Q604_bituminous_gravel,mean_Q605_concreting_gravel,mean_Q606_other_gravel,mean_Q607_constructional_fill
      movement_columns: movement_Q601_asphalting_sand,movement_Q602_building_soft_sand,movement_Q603_concreting_sand,movement_Q604_bituminous_gravel,movement_Q605_concreting_gravel,movement_Q606_other_gravel,movement_Q607_constructional_fill

  deploy-calculate-factors-wrangler:
    name: es-calculate-factors-wrangler
    handler: calculate_imputation_factors_wrangler.lambda_handler
    package:
      include:
        - calculate_imputation_factors_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      in_file_name: recalculate_means_out.json
      incoming_message_group: imputation-recalculate-means-out
      method_name: es-calculate-factors-method
      out_file_name: calculate_factors_out.json
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputation-calculate-factors-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-calculate-factors-method:
    name: es-calculate-factors-method
    handler: calculate_imputation_factors_method.lambda_handler
    package:
      include:
        - calculate_imputation_factors_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill
      first_threshold: 3
      second_threshold: 3
      third_threshold: 5
      first_imputation_factor: 1
      second_imputation_factor: 2
      third_imputation_factor: 1

  deploy-calculate-means-wrangler:
    name: es-calculate-means-wrangler
    handler: calculate_means_wrangler.lambda_handler
    package:
      include:
        - calculate_means_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      in_file_name: calculate_movement_out.json
      incoming_message_group: imputation-calculate-movement-out
      method_name: es-calculate-means-method
      out_file_name: calculate_means_output.json
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputatio-calculate-means-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-calculate-means-method:
    name: es-calculate-means-method
    handler: calculate_means_method.lambda_handler
    package:
      include:
        - calculate_means_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill
      movement_columns: movement_Q601_asphalting_sand,movement_Q602_building_soft_sand,movement_Q603_concreting_sand,movement_Q604_bituminous_gravel,movement_Q605_concreting_gravel,movement_Q606_other_gravel,movement_Q607_constructional_fill,region,strata

  deploy-calculate-movement-wrangler:
    name: es-calculate-movement-wrangler
    handler: calculate_movement_wrangler.lambda_handler
    package:
      include:
        - calculate_movement_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      current_segmentation: current_strata
      current_time: current_period
      in_file_name: previous_period_enriched_stratared.json
      incoming_message_group: strata-out
      method_name: es-calculate-movement-method
      non_response_file: non_responders_output.json
      out_file_name: calculate_movement_out.json
      output_file: non_responders_output.json
      previous_period_file: previous_period_enriched_stratared.json
      previous_segmentation: previous_strata
      previous_time: previous_period
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill
      reference: responder_id
      response_type: response_type
      segmentation: strata
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputation-calculate-movement-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo
      stored_segmentation: goodstrata
      time: period

  deploy-calculate-movement-method:
    name: es-calculate-movement-method
    handler: calculate_movement_method.lambda_handler
    package:
      include:
        - calculate_movement_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      current_period: 201809
      previous_period: 201806
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill

  deploy-iqrs-wrangler:
    name: es-iqrs-wrangler
    handler: iqrs_wrangler.lambda_handler
    package:
      include:
        - iqrs_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      in_file_name: calculate_means_out.json
      incoming_message_group: imputation-calculate-means-out
      iqrs_columns: iqrs601,iqrs602,iqrs603,iqrs604,iqrs605,iqrs606,iqrs607
      method_name: es-iqrs-method
      out_file_name: iqrs_out.json
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputation-iqrs-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

  deploy-iqrs-method:
    name: es-iqrs-method
    handler: iqrs_method.lambda_handler
    package:
      include:
        - iqrs_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      iqrs_columns: iqrs601,iqrs602,iqrs603,iqrs604,iqrs605,iqrs606,iqrs607
      movement_columns: movement_Q601_asphalting_sand,movement_Q602_building_soft_sand,movement_Q603_concreting_sand,movement_Q604_bituminous_gravel,movement_Q605_concreting_gravel,movement_Q606_other_gravel,movement_Q607_constructional_fill,region,strata

  deploy-recalculate-means-wrangler:
    name: es-recalculate-means-wrangler
    handler: recalculate_means_wrangler.lambda_handler
    package:
      include:
        - recalculate_means_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:es_python_marshmallow:2
      - arn:aws:lambda:eu-west-2:${self:custom.accountId}:layer:dev-es-commonfunctions:12
    tags:
      app: results
    environment:
      checkpoint: 3
      bucket_name: results-s3-bucket
      in_file_name: atypicals_out.json
      incoming_message_group: imputation-atypicals-out
      method_name: es-calculate-means-method
      out_file_name: recalculate_means_out.json
      questions_list: Q601_asphalting_sand,Q602_building_soft_sand,Q603_concreting_sand,Q604_bituminous_gravel,Q605_concreting_gravel,Q606_other_gravel,Q607_constructional_fill
      sns_topic_arn: arn:aws:sns:eu-west-2:${self:custom.accountId}:BMIResults
      sqs_message_group_id: imputation-recalculate-means-out
      sqs_queue_url: https://sqs.eu-west-2.amazonaws.com/${self:custom.accountId}/BMI_Results.fifo

plugins:
  - serverless-step-functions