---
service: es-imputation-sg
provider:
  name: aws
  role: arn:aws:iam::014669633018:role/lambda_invoke_lambda
  vpc:
    securityGroupIds:
      - ${file(../json_outputs/security_groups_output.json):SecurityGroups.0.GroupId}
    subnetIds:
      - ${file(../json_outputs/subnets_output.json):Subnets.0.VpcId}
      - ${file(../json_outputs/subnets_output.json):Subnets.1.VpcId}
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

functions:
  deploy-apply-factors-wrangler:
    name: es-apply-factors-wrangler
    handler: apply_factors_wrangler.lambda_handler
    package:
      include:
        - apply_factors_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      bucket_name: results-tf-vpc-s3
      s3_file: previous_period_enriched_stratared.json
      non_responder_file: non_responders_output.json
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: apply_factors_out
      method_name: es-apply-factors-method
      period: 201809

  deploy-apply-factors-method:
    name: es-apply-factors-method
    handler: apply_factors_method.lambda_handler
    package:
      include:
        - apply_factors_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo

  deploy-atypicals-wrangler:
    name: es-atypicals-wrangler
    handler: atypicals_wrangler.lambda_handler
    package:
      include:
        - atypicals_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: atypicals_out
      method_name: es-atypicals-method
      atypical_columns: atyp601,atyp602,atyp603,atyp604,atyp605,atyp606,atyp607

  deploy-atypicals-method:
    name: es-atypicals-method
    handler: atypicals_method.lambda_handler
    package:
      include:
        - atypicals_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      atypical_columns: atyp601,atyp602,atyp603,atyp604,atyp605,atyp606,atyp607
      iqrs_columns: iqrs601,iqrs602,iqrs603,iqrs604,iqrs605,iqrs606,iqrs607
      movement_columns: movement_Q601_asphalting_sand,movement_Q602_building_soft_sand,movement_Q603_concreting_sand,movement_Q604_bituminous_gravel,movement_Q605_concreting_gravel,movement_Q606_other_gravel,movement_Q607_constructional_fill
      mean_columns: mean_Q601_asphalting_sand,mean_Q602_building_soft_sand,mean_Q603_concreting_sand,mean_Q604_bituminous_gravel,mean_Q605_concreting_gravel,mean_Q606_other_gravel,mean_Q607_constructional_fill

  deploy-calculate-factors-wrangler:
    name: es-calculate-factors-wrangler
    handler: calculate_imputation_factors_wrangler.lambda_handler
    package:
      include:
        - calculate_imputation_factors_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: calculate_factors_out
      method_name: es-calculate-factors-method
      questions: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill

  deploy-calculate-factors-method:
    name: es-calculate-factors-method
    handler: calculate_imputation_factors_method.lambda_handler
    package:
      include:
        - calculate_imputation_factors_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      questions: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill
      first_threshold: 3
      second_threshold: 3
      third_threshold: 5
      first_imputation_factor: 1
      second_imputation_factor: 2
      third_imputation_factor: 1

  deploy-calculate-means-wrangler:
    name: es-calculate-factors-wrangler
    handler: calculate_means_wrangler.lambda_handler
    package:
      include:
        - calculate_means_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: calculate_means_out
      method_name: es-calculate-means-method
      questions_list: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill

  deploy-calculate-means-method:
    name: es-calculate-means-method
    handler: calculate_means_method.lambda_handler
    package:
      include:
        - calculate_means_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      questions_list: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill
      movement_columns: movement_Q601_asphalting_sand movement_Q602_building_soft_sand movement_Q603_concreting_sand movement_Q604_bituminous_gravel movement_Q605_concreting_gravel movement_Q606_other_gravel movement_Q607_constructional_fill region strata

  deploy-calculate-movement-wrangler:
    name: es-calculate-movement-wrangler
    handler: calculate_movement_wrangler.lambda_handler
    package:
      include:
        - calculate_movement_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      s3_file: previous_period_enriched_stratared.json
      bucket_name: results-tf-vpc-s3
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: calculate_movement_out
      method_name: es-calculate-movement-method
      time: period
      response_type: response_type
      questions_list: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill
      output_file: non_responders_output.json
      reference: responder_id
      segmentation: strata
      stored_segmentation: goodstrata
      current_time: current_period
      previous_time: previous_period
      current_segmentation: current_strata
      previous_segmentation: previous_strata

  deploy-calculate-movement-method:
    name: es-calculate-movement-method
    handler: calculate_movement_method.lambda_handler
    package:
      include:
        - calculate_movement_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      current_period: 201809
      previous_period: 201806
      questions_list: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill

  deploy-iqrs-wrangler:
    name: es-iqrs-wrangler
    handler: iqrs_wrangler.lambda_handler
    package:
      include:
        - iqrs_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: iqrs_out
      method_name: es-iqrs-method
      iqrs_columns: iqrs601,iqrs602,iqrs603,iqrs604,iqrs605,iqrs606,iqrs607

  deploy-iqrs-method:
    name: es-iqrs-method
    handler: iqrs_method.lambda_handler
    package:
      include:
        - iqrs_method.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      iqrs_columns: iqrs601,iqrs602,iqrs603,iqrs604,iqrs605,iqrs606,iqrs607
      movement_columns: movement_Q601_asphalting_sand movement_Q602_building_soft_sand movement_Q603_concreting_sand movement_Q604_bituminous_gravel movement_Q605_concreting_gravel movement_Q606_other_gravel movement_Q607_constructional_fill region strata

  deploy-recalculate-means-wrangler:
    name: es-recalculate-means-wrangler
    handler: recalculate_means_wrangler.lambda_handler
    package:
      include:
        - recalculate_means_wrangler.py
      exclude:
        - ./**
    layers:
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_layer:10
      - arn:aws:lambda:eu-west-2:014669633018:layer:es_python_marshmallow:2
    tags:
      app: results
    environment:
      queue_url: https://sqs.eu-west-2.amazonaws.com/014669633018/BMI_Results.fifo
      checkpoint: 3
      arn: arn:aws:sns:eu-west-2:014669633018:BMIResults
      sqs_messageid_name: recalc_means_out
      method_name: es-calculate-means-method
      questions_list: Q601_asphalting_sand Q602_building_soft_sand Q603_concreting_sand Q604_bituminous_gravel Q605_concreting_gravel Q606_other_gravel Q607_constructional_fill